### ISSUE TITLE
is it mallow-murder or mellow-murder?

### ISSUE THREAD

**Issue by theflyingrifle** [osum4est/mallow-murder#1]

**Comment by osum4est** [comment]
Wikipedia defines a marshm**a**llow as

> A marshmallow is a sugar-based confectionery that in its modern form typically consists of sugar, water and gelatin whipped to a squishy consistency, molded into small cylindrical pieces, and coated with corn starch.

This is spelled marshm**a**llow, not marshm**e**llo, so it is m**a**llow-muder!
